import type { Course } from '@/interfaces/course'

export const data: Array<Course> = [
  {
    id: 1,
    cover: '/images/products/original-cover.png',
    title: 'Trà sữa BOH Teh Tarik Vị Truyền Thống',
    rating: 5,
    ratingCount: 8,
    price: '169,000',
    category: 'Trà Sữa',
  },
  {
    id: 2,
    cover: '/images/products/ginger-cover.png',
    title: 'Trà sữa BOH Teh Tarik Vị Gừng',
    rating: 4.5,
    ratingCount: 12,
    price: '169,000',
    category: 'Trà Sữa',
  },
  {
    id: 3,
    cover: '/images/products/cham-cover.png',
    title: 'Trà sữa BOH Teh Tarik Vị Trà sữa Mix Cà phê',
    rating: 4.8,
    ratingCount: 10,
    price: '169,000',
    category: 'Trà Sữa',
  },
  {
    id: 4,
    cover: '/images/products/matcha-cover.png',
    title: 'Trà sữa BOH Teh Tarik Vị Matcha Latte',
    rating: 4.3,
    ratingCount: 15,
    price: '169,000',
    category: 'Trà Sữa',
  },
  {
    id: 5,
    cover: '/images/products/oats-cover.png',
    title: 'Trà sữa BOH Teh Tarik Vị Yến mạch',
    rating: 4.7,
    ratingCount: 9,
    price: '169,000',
    category: 'Trà Sữa',
  },
  {
    id: 6,
    cover: '/images/products/lemon-cover.png',
    title: 'Trà trái cây BOH Vị Chanh',
    rating: 4.9,
    ratingCount: 11,
    price: '139,000 VND',
    category: 'Trà Trái Cây',
  },
  {
    id: 7,
    cover: '/images/products/peach-cover.png',
    title: 'Trà trái cây BOH Vị Đào',
    rating: 4.5,
    ratingCount: 12,
    price: '139,000 VND',
    category: 'Trà Trái Cây',
  },
  {
    id: 8,
    cover: '/images/products/orchard-cover.png',
    title: 'Trà trái cây BOH Vị Trái Cây Nhiệt Đới',
    rating: 4.8,
    ratingCount: 10,
    price: '139,000 VND',
    category: 'Trà Trái Cây',
  },
]
